/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.CoordinadorControlador;
import controlador.EmpleadoControlador;
import controlador.FacturadorControlador;
import funciones.Encoder;
import funciones.Validaciones;
import java.util.logging.Logger;
import java.util.logging.Level;
import java.util.ArrayList;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Coordinador;
import modelo.Empleado;
import modelo.Facturador;

/**
 *
 * @author KATHE
 */
public class FacturadorVista extends javax.swing.JFrame {

    DefaultTableModel modelo;

    private int IdEmpleado;

    public FacturadorVista() {
        initComponents();
        this.setLocationRelativeTo(null);

        EmpleadoControlador empleadoControlador = new EmpleadoControlador();
        FacturadorControlador facturadorControlador = new FacturadorControlador();

        String[] titulosC = {"Item", "Cedula", "Nombres", "Apellidos", "Sexo", "Estado", "Dirección", "Telefono", "Correo", "Cargo", "Usuario", "Contrasena"};
        modelo = new DefaultTableModel(null, titulosC);
        tbUsuarioF.setModel(modelo);

        ArrayList<Empleado> empleado = new ArrayList<>();

        empleado = empleadoControlador.consultarEmp();
        for (int i = 0; i < empleado.size(); i++) {
            Object[] oEmp = {empleado.get(i).getIdEmpleado(), empleado.get(i).getCedula(), empleado.get(i).getNombre(), empleado.get(i).getApellido(), empleado.get(i).getSexo(), empleado.get(i).getEstado(), empleado.get(i).getDireccion(), empleado.get(i).getTelefono(), empleado.get(i).getCorreo(), empleado.get(i).getCargo(), empleado.get(i).getUsuario(), empleado.get(i).getContrasena()};
            modelo.addRow(oEmp);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        txtNombreF = new javax.swing.JTextField();
        txtApellidoF = new javax.swing.JTextField();
        txtCedulaF = new javax.swing.JTextField();
        txtSexoF = new javax.swing.JTextField();
        txtEstadoF = new javax.swing.JTextField();
        txtDireccionF = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        txtTelefonoF = new javax.swing.JTextField();
        txtCorreoF = new javax.swing.JTextField();
        txtCargoF = new javax.swing.JTextField();
        txtAreaF = new javax.swing.JTextField();
        txtUsuarioF = new javax.swing.JTextField();
        txtContrasenaF = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        btnCrearF = new javax.swing.JButton();
        btnActualizarF = new javax.swing.JButton();
        btnConsultarF = new javax.swing.JButton();
        btnEliminarF = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbUsuarioF = new javax.swing.JTable();
        btnRegresar1 = new javax.swing.JButton();
        btnRegresarF = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Gestión Empleados Facturador");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Empleado"));

        jLabel2.setText("Nombres:");

        jLabel3.setText("Apellidos:");

        jLabel4.setText("Cedula:");
        jLabel4.setToolTipText("");

        jLabel5.setText("Sexo:");

        jLabel6.setText("Estado Civil:");

        jLabel7.setText("Dirección:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNombreF)
                    .addComponent(txtApellidoF)
                    .addComponent(txtCedulaF)
                    .addComponent(txtSexoF)
                    .addComponent(txtEstadoF)
                    .addComponent(txtDireccionF, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtNombreF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtApellidoF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCedulaF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSexoF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEstadoF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDireccionF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7))
                        .addGap(29, 29, 29))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)))
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addGap(0, 27, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jLabel8.setText("Telefono:");

        jLabel9.setText("Correo:");

        jLabel10.setText("Cargo:");

        jLabel11.setText("Area");

        jLabel12.setText("Asignada:");

        jLabel14.setText("Usuario:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel12))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel14))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel14)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTelefonoF)
                    .addComponent(txtCorreoF)
                    .addComponent(txtCargoF)
                    .addComponent(txtAreaF, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                    .addComponent(txtUsuarioF)
                    .addComponent(txtContrasenaF))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(txtTelefonoF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCorreoF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCargoF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(txtAreaF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUsuarioF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtContrasenaF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jLabel15.setText("Contraseña:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel15)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel15))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        btnCrearF.setBackground(new java.awt.Color(240, 240, 240));
        btnCrearF.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        btnCrearF.setText("Crear");
        btnCrearF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearFActionPerformed(evt);
            }
        });

        btnActualizarF.setBackground(new java.awt.Color(240, 240, 240));
        btnActualizarF.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        btnActualizarF.setText("Actualizar");
        btnActualizarF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarFActionPerformed(evt);
            }
        });

        btnConsultarF.setBackground(new java.awt.Color(240, 240, 240));
        btnConsultarF.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        btnConsultarF.setText("Consultar");
        btnConsultarF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarFActionPerformed(evt);
            }
        });

        btnEliminarF.setBackground(new java.awt.Color(240, 240, 240));
        btnEliminarF.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        btnEliminarF.setText("Eliminar");
        btnEliminarF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addComponent(btnCrearF)
                .addGap(32, 32, 32)
                .addComponent(btnActualizarF)
                .addGap(43, 43, 43)
                .addComponent(btnConsultarF)
                .addGap(33, 33, 33)
                .addComponent(btnEliminarF)
                .addGap(28, 28, 28))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCrearF)
                    .addComponent(btnActualizarF)
                    .addComponent(btnConsultarF)
                    .addComponent(btnEliminarF))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        tbUsuarioF.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nombres", "Apellidos", "Cedula", "Sexo", "EstadoCivil", "Dirección", "Telefono", "Correo", "Cargo", "AreaAsignada"
            }
        ));
        jScrollPane1.setViewportView(tbUsuarioF);

        btnRegresar1.setBackground(new java.awt.Color(204, 204, 204));
        btnRegresar1.setText("Regresar");
        btnRegresar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 839, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel7Layout.createSequentialGroup()
                    .addGap(231, 231, 231)
                    .addComponent(btnRegresar1)
                    .addContainerGap(545, Short.MAX_VALUE)))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel7Layout.createSequentialGroup()
                    .addGap(79, 79, 79)
                    .addComponent(btnRegresar1)
                    .addContainerGap(89, Short.MAX_VALUE)))
        );

        btnRegresarF.setText("Regresar");
        btnRegresarF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarFActionPerformed(evt);
            }
        });

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Facturador.png"))); // NOI18N

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/LogoImportant.png"))); // NOI18N

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 0, 0));
        jLabel17.setText("Nota!");

        jLabel22.setText("En esta vista solo puede Consultar");

        jLabel21.setText("empleados con Cargo Facturador");

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/LogoRecordar.png"))); // NOI18N

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 0, 0));
        jLabel24.setText("Recordar!");

        jLabel18.setText("En el campo Area determine según aplique:");

        jLabel25.setText("Oriente, Occidente, Norte o Sur.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel23)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnRegresarF)
                                    .addGap(226, 226, 226)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel16))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel21)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(65, 65, 65)
                                .addComponent(jLabel17))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(69, 69, 69)
                                .addComponent(jLabel24))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(434, 434, 434)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnRegresarF)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(118, 118, 118)
                                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(132, 132, 132)
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel22)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel21)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel24)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel25)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void setIdEmpleado(int idE) throws SQLException {
        this.IdEmpleado = idE;
        mapearEmpleado();
    }

    private void mapearEmpleado() throws SQLException {
        EmpleadoControlador empleadoControlador = new EmpleadoControlador();
        Empleado empleado = new Empleado();
        empleado = empleadoControlador.consultarEmpleadoid(this.IdEmpleado);

        FacturadorControlador facturadorControlador = new FacturadorControlador();
        Facturador facturador = new Facturador();
        facturador = (Facturador) facturadorControlador.consultarEmpleadoid(this.IdEmpleado);

        int cedula = Integer.valueOf(empleado.getCedula());

        txtNombreF.setText(empleado.getNombre());
        txtApellidoF.setText(empleado.getApellido());
        txtCedulaF.setText(String.valueOf(cedula));
        txtSexoF.setText(empleado.getSexo());
        txtEstadoF.setText(empleado.getEstado());
        txtDireccionF.setText(empleado.getDireccion());
        txtTelefonoF.setText(empleado.getTelefono());
        txtCorreoF.setText(empleado.getCorreo());
        txtCargoF.setText(empleado.getCargo());
        txtUsuarioF.setText(empleado.getUsuario());
        txtContrasenaF.setText(empleado.getContrasena());
        txtAreaF.setText(facturador.getAreaAsignada());
    }

    private void btnRegresar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegresar1ActionPerformed

    private void btnRegresarFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarFActionPerformed
        TipoEmpleadoVista tipoEmpleadoVista = new TipoEmpleadoVista();
        tipoEmpleadoVista.setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegresarFActionPerformed

    private void btnCrearFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearFActionPerformed
        Validaciones validaciones = new Validaciones();
        Encoder encoder = new Encoder();
        try {
            if (!txtNombreF.getText().trim().equals("") && !txtApellidoF.getText().trim().equals("") && !txtTelefonoF.getText().trim().equals("")
                    && !txtSexoF.getText().trim().equals("") && !txtEstadoF.getText().trim().equals("") && !txtDireccionF.getText().trim().equals("")
                    && !txtCargoF.getText().trim().equals("") && !txtUsuarioF.getText().trim().equals("") && !txtContrasenaF.getText().trim().equals("")
                    && !txtAreaF.getText().trim().equals("")) {

                if (validaciones.ValidarEmail(txtCorreoF.getText())) {

                    if (txtTelefonoF.getText().length() >= 7) {

                        Empleado empleado = new Empleado();

                        EmpleadoControlador empleadoControlador = new EmpleadoControlador();

                        empleado.setNombre(txtNombreF.getText());
                        empleado.setApellido(txtApellidoF.getText());
                        empleado.setCedula(Integer.parseInt(txtCedulaF.getText()));
                        empleado.setSexo(txtSexoF.getText());
                        empleado.setEstado(txtEstadoF.getText());
                        empleado.setDireccion(txtDireccionF.getText());
                        empleado.setTelefono(txtTelefonoF.getText());
                        empleado.setCorreo(txtCorreoF.getText());
                        empleado.setCargo(txtCargoF.getText());
                        empleado.setUsuario(txtUsuarioF.getText());
                        empleado.setContrasena(encoder.encrypt(txtContrasenaF.getText()));;

                        Facturador facturador = new Facturador();

                        FacturadorControlador facturadorControlador = new FacturadorControlador();

                        facturador.setAreaAsignada(txtAreaF.getText());

                        boolean flag = empleadoControlador.crearUsuario(empleado);
                        if (flag) {
                            JOptionPane.showMessageDialog(null, "Usuario creado con Exito");
                            FacturadorVista facturadorVista = new FacturadorVista();
                            facturadorVista.setVisible(true);
                            this.dispose();
                        }

                        boolean flag3 = facturadorControlador.crearUsuario(facturador);
                        if (flag3) {
                            FacturadorVista facturadorVista = new FacturadorVista();
                            facturadorVista.setVisible(true);
                            this.dispose();
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "El telefono debe tener minimo 7 digitos");
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "El Correo debe tener un formato (ejemplo@xxxx.xx)");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Diligencia todos los campos");
            }
        } catch (Exception ex) {
            Logger.getLogger(CoordinadorVista.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnCrearFActionPerformed

    private void btnActualizarFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarFActionPerformed
        Empleado empleado = new Empleado();
        EmpleadoControlador empleadoControlador = new EmpleadoControlador();
        Facturador facturador = new Facturador();
        FacturadorControlador facturadorControlador = new FacturadorControlador();

        empleado.setIdEmpleado(this.IdEmpleado);
        empleado.setNombre(txtNombreF.getText());
        empleado.setApellido(txtApellidoF.getText());
        empleado.setCedula(Integer.parseInt(txtCedulaF.getText()));
        empleado.setSexo(txtSexoF.getText());
        empleado.setEstado(txtEstadoF.getText());
        empleado.setDireccion(txtDireccionF.getText());
        empleado.setTelefono(txtTelefonoF.getText());
        empleado.setCorreo(txtCorreoF.getText());
        empleado.setCargo(txtCargoF.getText());
        empleado.setUsuario(txtUsuarioF.getText());
        empleado.setContrasena(txtContrasenaF.getText());
        facturador.setIdEmpleado(this.IdEmpleado);
        facturador.setAreaAsignada(txtAreaF.getText());

        boolean flag = empleadoControlador.editarUsuario(empleado);
        if (flag) {
            JOptionPane.showMessageDialog(null, "Usuario Actualiado con Exito");
            FacturadorVista facturadorVista = new FacturadorVista();
            facturadorVista.setVisible(true);
            this.dispose();
        }

        boolean flag3 = facturadorControlador.editarUsuario(facturador);
        if (flag3) {
            FacturadorVista facturadorVista = new FacturadorVista();
            facturadorVista.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btnActualizarFActionPerformed

    private void btnConsultarFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarFActionPerformed
        if (tbUsuarioF.getSelectedRowCount() > 0) {
            FacturadorVista facturadorVista;
            try {
                facturadorVista = new FacturadorVista();
                int IdEmpleado = Integer.parseInt(tbUsuarioF.getValueAt(tbUsuarioF.getSelectedRow(), 0).toString());
                facturadorVista.setIdEmpleado(IdEmpleado);
                facturadorVista.setVisible(true);

            } catch (SQLException ex) {
                Logger.getLogger(TipoEmpleadoVista.class.getName()).log(Level.SEVERE, null, ex);
            }

            this.dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Debe selecionar un empleado de la tabla");
        }
    }//GEN-LAST:event_btnConsultarFActionPerformed

    private void btnEliminarFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarFActionPerformed
        EmpleadoControlador empleadoControlador = new EmpleadoControlador();
        FacturadorControlador facturadorControlador = new FacturadorControlador();

        boolean flag = empleadoControlador.eliminarUsuario(Integer.parseInt(tbUsuarioF.getValueAt(tbUsuarioF.getSelectedRow(), 0).toString()));

        boolean flag3 = facturadorControlador.eliminarUsuario(Integer.parseInt(tbUsuarioF.getValueAt(tbUsuarioF.getSelectedRow(), 0).toString()));

        if (flag) {
            System.out.println("Borrado con exito");
            JOptionPane.showMessageDialog(null, "Usuario borrado con exito");
            int count = modelo.getRowCount();
            for (int i = 0; i < count; i++) {
                modelo.removeRow(0);
            }
        }

        ArrayList<Empleado> empleado = new ArrayList<>();

        empleado = empleadoControlador.consultarEmp();
        for (int i = 0; i < empleado.size(); i++) {
            Object[] oEmp = {empleado.get(i).getIdEmpleado(), empleado.get(i).getCedula(), empleado.get(i).getNombre(), empleado.get(i).getApellido(), empleado.get(i).getSexo(), empleado.get(i).getEstado(), empleado.get(i).getDireccion(), empleado.get(i).getTelefono(), empleado.get(i).getCorreo(), empleado.get(i).getCargo(), empleado.get(i).getUsuario(), empleado.get(i).getContrasena()};
            modelo.addRow(oEmp);
        }
    }//GEN-LAST:event_btnEliminarFActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FacturadorVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FacturadorVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FacturadorVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FacturadorVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FacturadorVista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarF;
    private javax.swing.JButton btnConsultarF;
    private javax.swing.JButton btnCrearF;
    private javax.swing.JButton btnEliminarF;
    private javax.swing.JButton btnRegresar1;
    private javax.swing.JButton btnRegresarF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbUsuarioF;
    private javax.swing.JTextField txtApellidoF;
    private javax.swing.JTextField txtAreaF;
    private javax.swing.JTextField txtCargoF;
    private javax.swing.JTextField txtCedulaF;
    private javax.swing.JTextField txtContrasenaF;
    private javax.swing.JTextField txtCorreoF;
    private javax.swing.JTextField txtDireccionF;
    private javax.swing.JTextField txtEstadoF;
    private javax.swing.JTextField txtNombreF;
    private javax.swing.JTextField txtSexoF;
    private javax.swing.JTextField txtTelefonoF;
    private javax.swing.JTextField txtUsuarioF;
    // End of variables declaration//GEN-END:variables
}
