/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.CuadrillaControlador;
import controlador.EmpleadoControlador;
import controlador.ServicioControlador;
import funciones.Encoder;
import funciones.Validaciones;
import java.util.ArrayList;
import java.util.logging.Logger;
import java.util.logging.Level;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Cuadrilla;
import modelo.Empleado;
import modelo.ServicioGeneral;

/**
 *
 * @author KATHE
 */
public class ServicioGeneralVista extends javax.swing.JFrame {

    private final DefaultTableModel modelo;

    private int IdEmpleado;

    public ServicioGeneralVista() {
        initComponents();
        this.setLocationRelativeTo(null);

        EmpleadoControlador empleadoControlador = new EmpleadoControlador();
        ServicioControlador servicioControlador = new ServicioControlador();

        String[] titulosC = {"Item", "Cedula", "Nombres", "Apellidos", "Sexo", "Estado", "Dirección", "Telefono", "Correo", "Cargo", "Usuario", "Contrasena"};
        modelo = new DefaultTableModel(null, titulosC);
        tbUsuarioS.setModel(modelo);

        ArrayList<Empleado> empleado = new ArrayList<>();

        empleado = empleadoControlador.consultarEmp();
        for (int i = 0; i < empleado.size(); i++) {
            Object[] oEmp = {empleado.get(i).getIdEmpleado(), empleado.get(i).getCedula(), empleado.get(i).getNombre(), empleado.get(i).getApellido(), empleado.get(i).getSexo(), empleado.get(i).getEstado(), empleado.get(i).getDireccion(), empleado.get(i).getTelefono(), empleado.get(i).getCorreo(), empleado.get(i).getCargo(), empleado.get(i).getUsuario(), empleado.get(i).getContrasena()};
            modelo.addRow(oEmp);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnRegresarS = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        txtNombreS = new javax.swing.JTextField();
        txtApellidoS = new javax.swing.JTextField();
        txtCedulaS = new javax.swing.JTextField();
        txtSexoS = new javax.swing.JTextField();
        txtEstadoS = new javax.swing.JTextField();
        txtDireccionS = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        txtTelefonoS = new javax.swing.JTextField();
        txtCorreoS = new javax.swing.JTextField();
        txtCargoS = new javax.swing.JTextField();
        txtAreaS = new javax.swing.JTextField();
        txtUsuarioS = new javax.swing.JTextField();
        txtContrasenaS = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        btnCrearS = new javax.swing.JButton();
        btnActualizarS = new javax.swing.JButton();
        btnConsultarS = new javax.swing.JButton();
        btnEliminarS = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbUsuarioS = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Gestión Empleados Servicios Generales");
        jLabel1.setToolTipText("");

        btnRegresarS.setText("Regresar");
        btnRegresarS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarSActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Empleado"));

        jLabel2.setText("Nombres:");

        jLabel3.setText("Apellidos:");

        jLabel4.setText("Cedula:");

        jLabel5.setText("Sexo:");

        jLabel7.setText("Estado Civil:");

        jLabel8.setText("Dirección:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6))
                    .addComponent(jLabel8)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNombreS)
                    .addComponent(txtApellidoS)
                    .addComponent(txtCedulaS)
                    .addComponent(txtSexoS)
                    .addComponent(txtEstadoS)
                    .addComponent(txtDireccionS, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtNombreS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtApellidoS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCedulaS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSexoS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEstadoS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDireccionS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel9.setText("Telefono:");

        jLabel10.setText("Correo:");

        jLabel11.setText("Cargo:");

        jLabel12.setText("Area:");

        jLabel14.setText("Usuario:");

        jLabel15.setText("Contraseña:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addComponent(jLabel14)
                .addGap(18, 18, 18)
                .addComponent(jLabel15)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTelefonoS)
                    .addComponent(txtCorreoS, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtCargoS)
                    .addComponent(txtAreaS, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                    .addComponent(txtUsuarioS)
                    .addComponent(txtContrasenaS))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtTelefonoS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCorreoS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCargoS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtAreaS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUsuarioS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtContrasenaS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        btnCrearS.setBackground(new java.awt.Color(240, 240, 240));
        btnCrearS.setText("Crear");
        btnCrearS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearSActionPerformed(evt);
            }
        });

        btnActualizarS.setBackground(new java.awt.Color(240, 240, 240));
        btnActualizarS.setText("Actualizar");
        btnActualizarS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarSActionPerformed(evt);
            }
        });

        btnConsultarS.setBackground(new java.awt.Color(240, 240, 240));
        btnConsultarS.setText("Consultar");
        btnConsultarS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarSActionPerformed(evt);
            }
        });

        btnEliminarS.setBackground(new java.awt.Color(240, 240, 240));
        btnEliminarS.setText("Eliminar");
        btnEliminarS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarSActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(btnCrearS)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(btnActualizarS)
                .addGap(18, 18, 18)
                .addComponent(btnConsultarS)
                .addGap(18, 18, 18)
                .addComponent(btnEliminarS)
                .addGap(25, 25, 25))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCrearS)
                    .addComponent(btnActualizarS)
                    .addComponent(btnConsultarS)
                    .addComponent(btnEliminarS))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        tbUsuarioS.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nombres", "Apellidos", "Cedula", "Sexo", "EstadoCivil", "Dirección", "Telefono", "Correo", "Cargo", "Area"
            }
        ));
        jScrollPane1.setViewportView(tbUsuarioS);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 751, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(277, 277, 277))
        );

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Servicio.png"))); // NOI18N

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/LogoImportant.png"))); // NOI18N

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 0, 0));
        jLabel17.setText("Nota!");

        jLabel22.setText("En esta vista solo puede Consultar");

        jLabel21.setText("empleados con Cargo Servicio General");

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/LogoRecordar.png"))); // NOI18N

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 0, 0));
        jLabel24.setText("Recordar!");

        jLabel18.setText("En el campo Area determine según aplique:");

        jLabel25.setText("Cafeteria, Aseo o Recepción.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnRegresarS)
                        .addGap(180, 180, 180)
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel23)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel21)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(63, 63, 63)
                                                .addComponent(jLabel17))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(72, 72, 72)
                                                .addComponent(jLabel24))
                                            .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel25)
                                                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 21, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(361, 361, 361))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnRegresarS))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(116, 116, 116)
                                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(134, 134, 134)
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel22)
                                .addGap(4, 4, 4)
                                .addComponent(jLabel21)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel24)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel25))
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 190, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void setIdEmpleado(int idE) throws SQLException {
        this.IdEmpleado = idE;
        mapearEmpleado();
    }

    private void mapearEmpleado() throws SQLException {
        EmpleadoControlador empleadoControlador = new EmpleadoControlador();
        Empleado empleado = new Empleado();
        empleado = empleadoControlador.consultarEmpleadoid(this.IdEmpleado);

        ServicioControlador servicioControlador = new ServicioControlador();
        ServicioGeneral servicio = new ServicioGeneral();
        servicio = (ServicioGeneral) servicioControlador.consultarEmpleadoid(this.IdEmpleado);

        int cedula = Integer.valueOf(empleado.getCedula());

        txtNombreS.setText(empleado.getNombre());
        txtApellidoS.setText(empleado.getApellido());
        txtCedulaS.setText(String.valueOf(cedula));
        txtSexoS.setText(empleado.getSexo());
        txtEstadoS.setText(empleado.getEstado());
        txtDireccionS.setText(empleado.getDireccion());
        txtTelefonoS.setText(empleado.getTelefono());
        txtCorreoS.setText(empleado.getCorreo());
        txtCargoS.setText(empleado.getCargo());
        txtUsuarioS.setText(empleado.getUsuario());
        txtContrasenaS.setText(empleado.getContrasena());
        txtAreaS.setText(servicio.getAreaTrabajo());
    }

    private void btnRegresarSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarSActionPerformed
        TipoEmpleadoVista tipoEmpleadoVista = new TipoEmpleadoVista();
        tipoEmpleadoVista.setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegresarSActionPerformed

    private void btnCrearSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearSActionPerformed

        Validaciones validaciones = new Validaciones();
        Encoder encoder = new Encoder();

        try {
            if (!txtNombreS.getText().trim().equals("") && !txtApellidoS.getText().trim().equals("") && !txtCedulaS.getText().trim().equals("")
                    && !txtSexoS.getText().trim().equals("") && !txtEstadoS.getText().trim().equals("") && !txtDireccionS.getText().trim().equals("")
                    && !txtCargoS.getText().trim().equals("") && !txtUsuarioS.getText().trim().equals("") && !txtContrasenaS.getText().trim().equals("")
                    && !txtAreaS.getText().trim().equals("")) {

                if (validaciones.ValidarEmail(txtCorreoS.getText())) {
                    if (txtTelefonoS.getText().length() >= 7){                    

                        Empleado empleado = new Empleado();
                        EmpleadoControlador empleadoControlador = new EmpleadoControlador();

                        empleado.setNombre(txtNombreS.getText());
                        empleado.setApellido(txtApellidoS.getText());
                        empleado.setCedula(Integer.parseInt(txtCedulaS.getText()));
                        empleado.setSexo(txtSexoS.getText());
                        empleado.setEstado(txtEstadoS.getText());
                        empleado.setDireccion(txtDireccionS.getText());
                        empleado.setTelefono(txtTelefonoS.getText());
                        empleado.setCorreo(txtCorreoS.getText());
                        empleado.setCargo(txtCargoS.getText());
                        empleado.setUsuario(txtUsuarioS.getText());
                        empleado.setContrasena(encoder.encrypt(txtContrasenaS.getText()));

                        ServicioGeneral servicio = new ServicioGeneral();
                        ServicioControlador servicioControlador = new ServicioControlador();

                        servicio.setAreaTrabajo(txtAreaS.getText());

                        boolean flag = empleadoControlador.crearUsuario(empleado);
                        if (flag) {
                            JOptionPane.showMessageDialog(null, "Usuario creado con Exito");
                            ServicioGeneralVista servicioGeneralVista = new ServicioGeneralVista();
                            servicioGeneralVista.setVisible(true);
                            this.dispose();
                        }

                        boolean flag4 = servicioControlador.crearUsuario(servicio);
                        if (flag4) {
                            ServicioGeneralVista servicioGeneralVista = new ServicioGeneralVista();
                            servicioGeneralVista.setVisible(true);
                            this.dispose();
                        }

                    } else {
                        JOptionPane.showMessageDialog(null, "El telefono debe tener minimo 7 digitos");
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "El Correo debe tener un formato (ejemplo@xxxx.xx)");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Diligencia todos los campos");
            }
        } catch (Exception ex) {
            Logger.getLogger(CoordinadorVista.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnCrearSActionPerformed

    private void btnEliminarSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarSActionPerformed
        EmpleadoControlador empleadoControlador = new EmpleadoControlador();
        ServicioControlador servicioControlador = new ServicioControlador();

        boolean flag = empleadoControlador.eliminarUsuario(Integer.parseInt(tbUsuarioS.getValueAt(tbUsuarioS.getSelectedRow(), 0).toString()));

        boolean flag4 = servicioControlador.eliminarUsuario(Integer.parseInt(tbUsuarioS.getValueAt(tbUsuarioS.getSelectedRow(), 0).toString()));

        if (flag) {
            System.out.println("Borrado con exito");
            JOptionPane.showMessageDialog(null, "Usuario borrado con exito");
            int count = modelo.getRowCount();
            for (int i = 0; i < count; i++) {
                modelo.removeRow(0);
            }
        }

        ArrayList<Empleado> empleado = new ArrayList<>();

        empleado = empleadoControlador.consultarEmp();
        for (int i = 0; i < empleado.size(); i++) {
            Object[] oEmp = {empleado.get(i).getIdEmpleado(), empleado.get(i).getCedula(), empleado.get(i).getNombre(), empleado.get(i).getApellido(), empleado.get(i).getSexo(), empleado.get(i).getEstado(), empleado.get(i).getDireccion(), empleado.get(i).getTelefono(), empleado.get(i).getCorreo(), empleado.get(i).getCargo(), empleado.get(i).getUsuario(), empleado.get(i).getContrasena()};
            modelo.addRow(oEmp);
        }
    }//GEN-LAST:event_btnEliminarSActionPerformed

    private void btnActualizarSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarSActionPerformed
        Empleado empleado = new Empleado();
        EmpleadoControlador empleadoControlador = new EmpleadoControlador();

        ServicioGeneral servicio = new ServicioGeneral();
        ServicioControlador servicioControlador = new ServicioControlador();

        empleado.setIdEmpleado(this.IdEmpleado);
        empleado.setNombre(txtNombreS.getText());
        empleado.setApellido(txtApellidoS.getText());
        empleado.setCedula(Integer.parseInt(txtCedulaS.getText()));
        empleado.setSexo(txtSexoS.getText());
        empleado.setEstado(txtEstadoS.getText());
        empleado.setDireccion(txtDireccionS.getText());
        empleado.setTelefono(txtTelefonoS.getText());
        empleado.setCorreo(txtCorreoS.getText());
        empleado.setCargo(txtCargoS.getText());
        empleado.setUsuario(txtUsuarioS.getText());
        empleado.setContrasena(txtContrasenaS.getText());
        servicio.setIdEmpleado(this.IdEmpleado);
        servicio.setAreaTrabajo(txtAreaS.getText());

        boolean flag = empleadoControlador.editarUsuario(empleado);
        if (flag) {
            JOptionPane.showMessageDialog(null, "Usuario Actualiado con Exito");
            ServicioGeneralVista servicioGeneralVista = new ServicioGeneralVista();
            servicioGeneralVista.setVisible(true);
            this.dispose();
        }

        boolean flag4 = servicioControlador.editarUsuario(servicio);
        if (flag4) {
            ServicioGeneralVista servicioGeneralVista = new ServicioGeneralVista();
            servicioGeneralVista.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btnActualizarSActionPerformed

    private void btnConsultarSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarSActionPerformed
        if (tbUsuarioS.getSelectedRowCount() > 0) {
            ServicioGeneralVista servicioGeneralVista;
            try {
                servicioGeneralVista = new ServicioGeneralVista();
                int IdEmpleado = Integer.parseInt(tbUsuarioS.getValueAt(tbUsuarioS.getSelectedRow(), 0).toString());
                servicioGeneralVista.setIdEmpleado(IdEmpleado);
                servicioGeneralVista.setVisible(true);

            } catch (SQLException ex) {
                Logger.getLogger(TipoEmpleadoVista.class.getName()).log(Level.SEVERE, null, ex);
            }

            this.dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Debe selecionar un empleado de la tabla");
        }
    }//GEN-LAST:event_btnConsultarSActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ServicioGeneralVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ServicioGeneralVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ServicioGeneralVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ServicioGeneralVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ServicioGeneralVista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarS;
    private javax.swing.JButton btnConsultarS;
    private javax.swing.JButton btnCrearS;
    private javax.swing.JButton btnEliminarS;
    private javax.swing.JButton btnRegresarS;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbUsuarioS;
    private javax.swing.JTextField txtApellidoS;
    private javax.swing.JTextField txtAreaS;
    private javax.swing.JTextField txtCargoS;
    private javax.swing.JTextField txtCedulaS;
    private javax.swing.JTextField txtContrasenaS;
    private javax.swing.JTextField txtCorreoS;
    private javax.swing.JTextField txtDireccionS;
    private javax.swing.JTextField txtEstadoS;
    private javax.swing.JTextField txtNombreS;
    private javax.swing.JTextField txtSexoS;
    private javax.swing.JTextField txtTelefonoS;
    private javax.swing.JTextField txtUsuarioS;
    // End of variables declaration//GEN-END:variables
}
